import test from 'node:test';
import assert from 'node:assert/strict';
import {createApp} from '../app.js';
import {validState,validDate} from '../validation.js';

test('authentication, persistence API, conflicts, validation and logout', async t=>{
  let state={version:0,events:[],holidayOverrides:{}};
  const store={health:async()=>{},get:async()=>structuredClone(state),put:async input=>{if(input.version!==state.version)return;state=structuredClone({...input,version:state.version+1});return state;}};
  const origin='http://localhost:3000';
  const server=createApp({store,password:'a-private-password-123',secret:'s'.repeat(40),origin,secure:false});
  await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
  t.after(()=>{server.closeAllConnections();server.close();});
  const base='http://127.0.0.1:'+server.address().port;
  const request=(path,method='GET',body,cookie='',requestOrigin=origin)=>fetch(base+path,{method,headers:{origin:requestOrigin,'content-type':'application/json',cookie},body:body===undefined?undefined:JSON.stringify(body)});
  assert.equal((await request('/healthz')).status,200);
  assert.equal((await request('/api/state')).status,401);
  assert.equal((await request('/api/login','POST',{password:'wrong'})).status,401);
  assert.equal((await request('/api/login','POST',{password:'a-private-password-123'},'','https://evil.example')).status,403);
  const login=await request('/api/login','POST',{password:'a-private-password-123'});
  assert.equal(login.status,200);
  assert.match(login.headers.get('set-cookie'),/HttpOnly; SameSite=Strict/);
  const cookie=login.headers.get('set-cookie').split(';')[0];
  assert.equal((await request('/api/state','GET',undefined,cookie+'x')).status,401);
  const initial=await (await request('/api/state','GET',undefined,cookie)).json();
  assert.deepEqual(initial,state);
  const entry={id:'test-id',date:'2026-09-23',title:'회의 <script>',time:'14:30'};
  const update={version:0,events:[entry],holidayOverrides:{'2026-09-24':{type:'temporary',name:'휴일'}}};
  assert.equal((await request('/api/state','PUT',update,cookie)).status,200);
  assert.deepEqual((await (await request('/api/state','GET',undefined,cookie)).json()).events,[entry]);
  assert.equal((await request('/api/state','PUT',update,cookie)).status,409);
  assert.equal((await request('/api/state','PUT',{...update,version:1,events:[{...entry,date:'2026-02-30'}]},cookie)).status,400);
  assert.equal((await request('/api/state','PUT',{...update,version:1},cookie,'https://evil.example')).status,403);
  const writes=await Promise.all([request('/api/state','PUT',{...update,version:1},cookie),request('/api/state','PUT',{...update,version:1},cookie)]);
  assert.deepEqual(writes.map(r=>r.status).sort(),[200,409]);
  assert.equal((await request('/api/state','PUT',{version:2,events:[],holidayOverrides:{}},cookie)).status,200);
  assert.equal(state.events.length,0);
  assert.equal((await request('/.env')).status,404);
  const page=await request('/');assert.equal(page.status,200);assert.match(page.headers.get('content-security-policy'),/frame-ancestors 'none'/);
  assert.match(await page.text(),/cloud.js/);
  const logout=await request('/api/logout','POST',{},cookie);assert.match(logout.headers.get('set-cookie'),/Max-Age=0/);
  assert.equal((await request('/api/state')).status,401);
  for(let i=0;i<20;i++)assert.equal((await request('/api/login','POST',{password:'wrong'})).status,401);
  assert.equal((await request('/api/login','POST',{password:'wrong'})).status,429);
});
test('strict calendar validation',()=>{
  assert.equal(validDate('2024-02-29'),true);assert.equal(validDate('2026-02-29'),false);
  assert.equal(validDate('0000-01-01'),false);
  const e={id:'a',title:'ok',date:'2026-09-23',time:''};
  const s={version:0,events:[e],holidayOverrides:{}};
  assert.equal(validState(s),true);
  for(const change of [{time:'24:00'},{title:' '},{date:'2026-13-01'}])assert.equal(validState({...s,events:[{...e,...change}]}),false);
  assert.equal(validState({...s,events:[e,e]}),false);
  assert.equal(validState({...s,holidayOverrides:{'__bad__':{type:'public',name:'x'}}}),false);
  assert.equal(validState({...s,holidayOverrides:{'2026-09-23':{type:'public',name:''}}}),false);
});
